### PR TITLE
Conditional ring bonus

### PR DESCRIPTION
**Pull request by Kaniabi**
This first pull request implement the conditional ring bonus.

This implementation serves as a test of concept for the real one. I would like to discuss with you before any bigger effort.

The idea is to add these conditional ring bonuses on the data-packs and implement the necessary support on the code.
* Adding the "usage" parameter to "get_ring_rank" ;
* Implement the usage to obtain the data from the character model;
* Change the data-pack model to support these new kind of entries;
* Edit the data-packs to include these bonuses where necessary.

### CODE REVIEW

**Comment by OpenNingia** [comment]
I won't merge this pull request immediately, because I'm moving all the logic from the `CharacterModel` class into the api functions ( get_ring_rank method is going to disappear from the `CharacterModel` ).

The reason behind this is that there are lots of hacks in `CharacterModel` to apply various mechanical rules that shouldn't exists.

Still, for the sake of discussion, can you explain me a use case where this implementation is needed? 
The usages are always two ( i.e. normal and kiho ) or there are more?

**Comment by Kaniabi** [comment]
I believed that there was more cases where the ring changes depending on a condition. Searching and thinking more about it I've found out that this is not that common.

Anyway, the idea is to move this kind of "conditional ring bonus" to the data-packs, instead of hard coding it. The use case we have it the "Studend of Hitsu-do" alternate path, that grants the player a +1 fire ring bonus for buying kihos. I've made the necessary changes on both DAL and l5r-data-packs to implement that.

The real problem we want to solve, that this one we found more cases, it is not "ring bonus" but attack and damage bonuses granted by some classes/perks/techniques and not implemented automatically. For example we have a monk that have a lot of bonuses for unarmed attacks/damages granted by its schools/perks but these bonuses had to be set using manual modifiers. I would like to replace these manual modifiers by rules defined in the data-pack. By the way, this will be my next pull request. :-)

**Comment by OpenNingia** [comment]
In case of attack/damage bonus a simple approach would be to automatically add a modifier item upon rank advancement. 

That could be done by adding a `modifiers` field to the `advancement.rank.Rank` object, and modify the `get_modifiers` function in order to retrieve those modifiers.

The general rule would be to add anything that is gained with a rank advancement in that structure, because that way it remain consistent when you undo the advancement.

Instead, for those exception to the basic rules ( like +1 fire ring to kiho purchase ), I usually hardcode the rule. Here an example:

```language-python
    # check monks_walk_with_the_prophet
    if api.character.has_tag_or_rule('monks_walk_with_the_prophet'):
        # the first 3 kiho should be of the same element
        if 0 < len(other_kiho) < 3:
            first_kiho_element = other_kiho[0].element

            if first_kiho_element != kiho_.element:
                return False, api.tr("Your initial Kiho must be selected from the same element")
        if len(other_kiho) < 3:
            against_mastery += 1
```

**Comment by Kaniabi** [comment]
Hi there,

Created another pull-request with the hard-coded implementation of the conditional ring bonus for kihos.

You can close/cancel this one.

**Comment by OpenNingia** [comment]
ok, closing this one

**Pull request closed without merging**
